DROP TABLE ORDERITEM IF EXISTS
DROP TABLE CUSTOMERORDER IF EXISTS
DROP TABLE PRODUCT IF EXISTS
DROP TABLE PRODUCT_CATEGORY IF EXISTS
DROP TABLE CUSTOMER IF EXISTS

CREATE TABLE CUSTOMER(EMAIL_ADDRESS VARCHAR(100) NOT NULL PRIMARY KEY,PASSWORD VARCHAR(50) NOT NULL,SECRET_QUESTION VARCHAR(500) NOT NULL,SECRET_ANSWER VARCHAR(500) NOT NULL,FIRST_NAME VARCHAR(50) NOT NULL,LAST_NAME VARCHAR(50) NOT NULL,ADDRESS VARCHAR(100) NOT NULL,ADDRESS2 VARCHAR(100) NOT NULL,CITY VARCHAR(100) NOT NULL,STATE VARCHAR(20) NOT NULL,ZIP_CODE VARCHAR(20), PHONE_NUMBER VARCHAR(20))
CREATE TABLE PRODUCT_CATEGORY(CATEGORY_ID BIGINT NOT NULL PRIMARY KEY, CATEGORY_NAME VARCHAR(100))
CREATE TABLE PRODUCT(PRODUCT_ID BIGINT NOT NULL PRIMARY KEY, MAKE VARCHAR(100), MODEL VARCHAR(100), DESCRIPTION VARCHAR(10000), SRC VARCHAR(100), CATEGORY_ID BIGINT, STATUS VARCHAR(20), QUANTITY BIGINT NOT NULL, UNITPRICE DOUBLE NOT NULL, is_FEATURED BIGINT ,CREATED_DT DATE, CONSTRAINT SYS_FK_57 FOREIGN KEY(CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(CATEGORY_ID))
CREATE TABLE CUSTOMERORDER(ORDERID BIGINT NOT NULL PRIMARY KEY,EMAIL_ADDRESS VARCHAR(50) NOT NULL,STATUS VARCHAR(50) NOT NULL,TOTALCOST DOUBLE NOT NULL,ORDERDATE DATE NOT NULL,CONSTRAINT SYS_FK_50 FOREIGN KEY(EMAIL_ADDRESS) REFERENCES CUSTOMER(EMAIL_ADDRESS))
CREATE TABLE ORDERITEM(ITEMID BIGINT NOT NULL PRIMARY KEY,PRODUCT_ID BIGINT NOT NULL,ORDERID BIGINT NOT NULL,QUANTITY BIGINT,CONSTRAINT SYS_FK_55 FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),CONSTRAINT SYS_FK_56 FOREIGN KEY(ORDERID) REFERENCES CUSTOMERORDER(ORDERID))
